### ISSUE TITLE
Release the docker image to GitHub Container registry

### ISSUE THREAD

**Issue by gKits** [clupasq/word-mastermind#10]
I think it would be really cool if you could just pull the image from the GitHub CR.

It only requires a simple GitHub Action Pipeline that does not need any configuration.
Afterwards you should create a new release with a new tag (maybe just 0.0.1) and set the visibility of the release package to public.

**Comment by gKits** [comment]
I have already created a pull request #11

**Comment by clupasq** [comment]
Hey, thanks a lot for this contribution!

I merged it and will attempt to make a release now.
